#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop ceph.target >/dev/null
fi
# End automatically added section

# Automatically added by dh_python2:
if which pyclean >/dev/null 2>&1; then
	pyclean -p ceph-common 
else
	dpkg -L ceph-common | grep \.py$ | while read file
	do
		rm -f "${file}"[co] >/dev/null
  	done
fi

# End automatically added section
